from dotenv import load_dotenv
load_dotenv()


from langchain_mistralai import ChatMistralAI
from langchain.tools import tool


#Tool
@tool
def get_text_length(text: str) -> int:
    """Returns the number of character in a given text"""
    return len(text)

#LLM
llm = ChatMistralAI(model = "mistral-small-2506")
llm_with_tool = llm.bind_tools([get_text_length])

# Step 1: LLM decides tool
result = llm_with_tool.invoke(
    "Use the get_text_length tool to find the length of: hello how are you"
)


# Step 2-4: Execute tool
if result.tool_calls:
    tool_call = result.tool_calls[0]
    tool_result = get_text_length.invoke(tool_call["args"])

    # Step 5: Send back to LLM
    final_response = llm.invoke(
        f"The result of the text is {tool_result}"
    )

    print(final_response.content)


#OUTPUT >>

# It looks like you're referring to a result or calculation that equals **17**. Could you clarify what you're asking about? For example:

# - Are you looking for an explanation of how to get **17** as a result?
# - Or is this part of a math problem, puzzle, or another context?
# - Do you need help solving something that leads to the answer **17**?



# Here we are sending result of "get_text_length" tool directly to our llm >> now also our AI is not able to understand much

# But if we see in real world senario >> we have to maintain history >>
# we have to see tool_result, humman_message, AI_message >> we have to create history of all these >> THAT IS KNOWN AS MESSAGE HISTORY 
# REASON >> SO THAT OUR LLM KNEW (WHAT QUERY USER ASKED), (WHAT IT GENERATED BY ITS OWN), (AND WHAT IS AGIAN GENERATED BY TOOL), SO IT  ANSWER BY COMBINING ALL OF THESE